### ISSUE TITLE
ya no se organizan?

### ISSUE THREAD

**Issue by juanbrujo** [beerjs/mexicocity#4]
Hola, organizo [BeerJS Santiago](https://github.com/beerjs/santiago). Estaré todo Julio en CDMX, quisiera conocer a la comunidad alrededor del front-end. Me ayudas a ver si hay eventos durante el mes? Muy agradecido desde ya.

**Comment by Siedrix** [comment]
El evento paso a llamarse EventLoop, pasa el primer miercoles de cada mes. Revisa https://www.meetup.com/eventloop/ o en http://chat.javascriptmx.com puedes entrar al chat de la comunidad y preguntar por mas eventos.
